name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - name: Release Please Bot
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.GA_ACCESS_TOKEN }}